### ISSUE TITLE
worked version

### ISSUE THREAD

**Issue by mibamur** [opal/opal-playground#1]
Hello!

this the same http://opalrb.org/opal-playground/ without React

@fkchang http://fkchang.github.io/opal-playground/  broken? could you allow issues?

**Comment by fkchang** [comment]
@mibamur I did fork http://opalrb.org/opal-playground/ 

There is a bug I need to fix that I recently introduced on http://fkchang.github.io/opal-playground/ , maybe I should revert, feel free to submit issues on https://github.com/fkchang/opal-playground

**Comment by mibamur** [comment]
you should turnON issues https://github.com/fkchang/opal-playground in Settings
https://help.github.com/articles/disabling-issues/

**Comment by fkchang** [comment]
@mibamur oops, sorry, didn't know it was off.  My other repos had it on automatically - it's on now
